### ISSUE TITLE
Debugger doesn't start

### ISSUE THREAD

**Issue by stkarabe** [SqrTT/prophet#126] opened 2018-08-30 09:37 UTC
Hi,

When I start the debugger for the first time I get the following message:
![image](https://user-images.githubusercontent.com/37329795/44843516-c951bc80-ac48-11e8-888a-761bc5a11b20.png).

The next time I tried to start it (without restarting the session), I get: 
"There is already a debug configuration "Sandbox" running."

I have tried to uninstall/reinstall the extension as well as the code itself but didn't work.

Any suggestions?

**Comment by SqrTT** [comment] 2018-08-30 09:46
this is duplicate of #122 . closing.

**Closed by SqrTT** 2018-08-30 09:46 UTC
