### ISSUE TITLE
Clean debug breakpoints.

### ISSUE THREAD

**Issue by zeeshan1001** [SqrTT/prophet#89] opened 2018-03-15 09:51 UTC
As a developer,

I would like to have a feature added to remove all active remote breakpoints (Clear breakpoints) so that whenever my debugger is stuck, I could clear the breakpoints.

**Comment by SqrTT** [comment] 2018-03-15 10:11
Hi @zeeshan1001 
Are you talking about this buttons?

![image](https://user-images.githubusercontent.com/1271300/37457191-ecedc78e-2849-11e8-8516-3ac65851b43e.png)

**Comment by zeeshan1001** [comment] 2018-03-15 11:29
These buttons remove breakpoints locally from the editor (I assume). However, sometimes the debugger gets hung on a breakpoint remotely even if you clear all breakpoints locally from your editor. I would like to clear all from remote so that the execution can continue. I know there is a way to clean breakpoints in the SDAPI 2.0

**Comment by SqrTT** [comment] 2018-03-15 11:41
Those buttons remove breakpoints on the backend too (not only form UI).
Or are you facing debugger to stop on ghost/removed breakpoint?

**Comment by SqrTT** [comment] 2018-03-15 11:43
PS. `DELETE http://hostname:port/dw/debugger/v2_0/client` is same as restarting debugger. It is used when the debugger is shooting down.

**Comment by SqrTT** [comment] 2018-03-15 11:46
Probably you are referring to the issue #42. If so there are to fix it on the extension side.

**Comment by zeeshan1001** [comment] 2018-03-15 11:46
Yes, its happening to me a lot. When I start the debugger and it halts on a breakpoint, if I try to move to next line, it just stays there (gets stuck) and the instance gets hung. To fix this I have to restart the sandbox every time. My team is facing this problem a lot and developers are getting discouraged from using VSCode as an alternative to Eclipse.

**Comment by SqrTT** [comment] 2018-03-15 11:47
Probably you are referring to the issue #42. If so there are no fix it on the extension side.

**Comment by SqrTT** [comment] 2018-03-16 14:27
closing since this is duplicate of #42

**Closed by SqrTT** 2018-03-16 14:27 UTC

**Comment by SqrTT** [comment] 2018-03-16 14:29
fix for this issue require the involvement of SCFF side which I can't affect through.
