### ISSUE TITLE
ISML Server use 100% CPU 

### ISSUE THREAD

**Issue by rmkpatchaa-sfdc** [SqrTT/prophet#191] opened 2019-09-24 15:26 UTC
Every time I open a project with isml templates in it, my CPU is used à 100%.
When I quit the VSCode Helper process, I have these error messages : 
```
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
[Error - 4:24:09 PM] Connection to server is erroring. Shutting down server.
```
And I can't correctly work with ISML files again. When I restart VSCode, CPU usage gets back to 100%.

**Comment by tonygustafsson** [comment] 2019-09-26 13:35
@rmkpatchaa-sfdc Are you using Linux? I'm also a user of Prophet and I have lots of issues with my whole system hanging when coding against SFCC. Haven't heard any issues for Windows users - but my college had the same issue as well using Linux a while back.

**Comment by SqrTT** [comment] 2019-09-26 15:10
Hi @rmkpatchaa-sfdc 
Thank you for reporting.
Could you please track down what exact isml template is causing hangup? 
Or is there some way to reproduce the issue?

Also could you please try to disable other extensions to make sure the extension is a reason of 100% CPU?

PS. Linux system is not reason for such behavior. The extension is build on Linux and works smoothly (at least I see no issues with performance).

**Comment by rmkpatchaa-sfdc** [comment] 2019-09-26 21:50
@SqrTT I've tried to disable all extensions. 
I Still have the CPU problem.
Here is the screenshot: https://photos.app.goo.gl/ECtdxZPcbWRov5tq8

**Comment by tonygustafsson** [comment] 2019-09-27 06:45
I've done some tests now.
- I can upload cartridge without any problem.
- I can save controllers.
- I can save client javascript.
- I can save _some_ ISML files.

So I created a new ISML file with simple HTML. Was ok. I added some if statements, added elseif and else. Added a few variables like ${'string'} without probelms. But as soon as I add isscript (even without content) the CPU goes through the roof.

I know that isscript is not the best way of going about things, but sometimes (like loops) it's very practical. If we would stop using this it would end up with really complex backend code instead.

The next step would be to download the source code and debug the extension. Don't know If I've got the time. But if I do, I will keep you posted.

**Comment by rmkpatchaa-sfdc** [comment] 2019-09-27 08:50
Actually I don't have any isscript in the file causing issues...
Here's the code : 
```
<isif
    condition="${pageContext.ns != 'var1' && pageContext.ns != 'var2' && pageContext.ns != 'var3' && pageContext.ns !=
               'var4' && pageContext.ns != 'var5' && pageContext.ns != 'var6' && pageContext.ns != 'var7' &&
               pageContext.ns != 'var8' && pageContext.ns != 'var9' && pageContext.ns != 'var10' && pageContext.ns !=
               'var11' && pageContext.ns != 'var12'}">
    <title>${pdict.CurrentPageMetaData.title + ' ' + Resource.msg('global.meta', 'locale', null)}</title>
    <meta property="og:title"
        content="${pdict.CurrentPageMetaData.title + ' ' + Resource.msg('global.meta', 'locale', null)}" />
    <meta property="title"
        content="${pdict.CurrentPageMetaData.title + ' ' + Resource.msg('global.meta', 'locale', null)}" />
    <isif condition="${pageContext.ns == 'content' && pageContext.code != ''}">
        <isset name="Content" value="${dw.content.ContentMgr.getContent(pageContext.code)}" scope="page" />
        <isif condition="${!empty(Content)}">
            <isif condition="${!empty(pdict.CurrentPageMetaData.description)}">
                <isset name="dept" value="${pdict.CurrentPageMetaData.description}" scope="page" />
            <iselseif condition="${!empty(Content.custom.body)}" />
                <isset name="dept" value="${Content.custom.body.toString().replace(/<[^><]*>/g, '')}" scope="page" />
            <iselseif condition="${!empty(Content.custom.yk_structured_body1)}" />
                <isset name="dept" value="${Content.custom.yk_structured_body1.toString().replace(/<[^><]*>/g, '')}"
                    scope="page" />
            <iselseif condition="${!empty(Content.custom.yk_structured_body2)}" />
                <isset name="dept" value="${Content.custom.yk_structured_body2.toString().replace(/<[^><]*>/g, '')}"
                    scope="page" />
            </isif>
            <meta name="description" content="${dept.toString().substr(0, 100)}" />
        </isif>
    </isif>
<iselse/>
    <isif condition="${pageContext.ns == 'var2'}">
        <isif condition="${pdict.productSearch != null && pdict.productSearch.searchKeywords != null}">
            <title>${pdict.productSearch.searchKeywords + ' ' + Resource.msg('global.meta', 'locale', null)}</title>
            <meta property="og:title"
                content="${pdict.productSearch.searchKeywords + ' ' + Resource.msg('global.meta', 'locale', null)}" />
            <meta property="title"
                content="${pdict.productSearch.searchKeywords + ' ' + Resource.msg('global.meta', 'locale', null)}" />
        <iselse/>
            <title>
                <isprint value="${pdict.CurrentPageMetaData.title}" encoding="off" />
            </title>
            <meta property="og:title" content="${pdict.CurrentPageMetaData.title}" />
            <meta property="title" content="${pdict.CurrentPageMetaData.title}" />
            <isif condition="${!empty(pdict.CurrentPageMetaData.description)}">
                <meta name="description" content="${pdict.CurrentPageMetaData.description}" />
            <iselse/>
                <meta name="description" content="" />
            </isif>
        </isif>
    <iselseif condition="${pageContext.ns == 'var11'}" />
        <title>
            <isprint
                value="${Resource.msg('page.title', 'var11', null) + ' ' + Resource.msg('global.meta', 'locale', null)}"
                encoding="off" />
        </title>
        <meta property="og:title"
            content="${Resource.msg('page.title', 'var11', null) + ' ' + Resource.msg('global.meta', 'locale', null)}" />
        <meta property="title"
            content="${Resource.msg('page.title', 'var11', null) + ' ' + Resource.msg('global.meta', 'locale', null)}" />
        <meta name="description"
            content="${Resource.msg('page.description', 'var11', null) + ' ' + Resource.msg('global.meta', 'locale', null)}" />
    <iselse/>
        <title>
            <isprint value="${pdict.CurrentPageMetaData.title}" encoding="off" />
        </title>
        <meta property="og:title" content="${pdict.CurrentPageMetaData.title}" />
        <meta property="title" content="${pdict.CurrentPageMetaData.title}" />
        <isif condition="${!empty(pdict.CurrentPageMetaData.description)}">
            <meta name="description" content="${pdict.CurrentPageMetaData.description}" />
        <iselse/>
            <meta name="description" content="" />
        </isif>
    </isif>
</isif>
<meta name="keywords" content="${pdict.CurrentPageMetaData.keywords ? pdict.CurrentPageMetaData.keywords : ''}" />

<iscomment>Additional Rule based page meta tags</iscomment>
<isloop items="${pdict.CurrentPageMetaData.pageMetaTags}" var="pageMetaTag">
    <isif condition="${pageMetaTag.name}">
        <meta name='<isprint value="${pageMetaTag.ID}">' content='<isprint value="${pageMetaTag.content}">'>
    <iselseif condition="${pageMetaTag.property}" />
        <meta property='<isprint value="${pageMetaTag.ID}">' content='<isprint value="${pageMetaTag.content}">'>
    </isif>
</isloop>
```

I've just changed real values with `**varx**` in the code.

**Comment by SqrTT** [comment] 2019-09-27 09:18
thanks for code example. Unfortunately, I don't have issues with provided code...

**Comment by rmkpatchaa-sfdc** [comment] 2019-09-27 11:12
Have you tried to edit the file (just add a new line) and save? 
For me, it happens when I edit the file.
For more information, here is `code --status` output ... 

```
Version:          Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS Version:       Darwin x64 18.7.0
CPUs:             Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)
Memory (System):  16.00GB (1.33GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     enabled
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	   115	 37750	code main
    0	    66	 37751	   gpu-process
    0	   262	 37753	   window (htmlHeadMeta.isml — Untitled (Workspace))
    0	   197	 38167	     extensionHost
    0	    49	 38180	       electron_node server.js
    0	    49	 38212	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=38167
  103	    49	 38237	       electron_node ismlServer.js
    0	    49	 38168	     watcherService
    0	    49	 38173	     searchService
    0	   115	 38169	   shared-process
    0	     0	 40491	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

**Comment by SqrTT** [comment] 2019-10-01 09:58
yes, I've tried to edit (and play around) - no intensive CPU usage.
Could you please share your User and Workspace preference?
(along with `.htmlhintrc` in case it present.)

**Comment by rmkpatchaa-sfdc** [comment] 2019-10-01 10:04
**settings.json :** 
```
{
    "files.autoSave": "onFocusChange",
    "editor.formatOnSave": true,
    "editor.fontFamily": "'Fira Code', 'Operator Mono', 'iA Writer Duospace', 'Source Code Pro', Menlo, Monaco, monospace",
    "editor.fontLigatures": true,
    "editor.detectIndentation": true,
    "editor.renderIndentGuides": false,
    // disable editor formatting, so eslint can handle it
    // "[javascript]": {
    //     "editor.formatOnSave": false,
    //     "editor.defaultFormatter": "vscode.typescript-language-features",
    // },
    "[xml]": {
        "editor.formatOnSave": false,
        "editor.defaultFormatter": "DotJoshJohnson.xml",
    },
    "jshint.options": {
        "esversion": 6
    },
    // "javascript.validate.enable": false,
    // Enable auto-updating of import paths when you rename a file.    
    "javascript.updateImportsOnFileMove.enabled": "always",
    "jshint.enable": false,
    // available through eslint plugin in vscode
    "eslint.autoFixOnSave": true,
    "eslint.alwaysShowStatus": true,
    "eslint.packageManager": "yarn",
    "explorer.confirmDelete": false,
    "breadcrumbs.enabled": true,
    "typescript.validate.enable": false,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "jsx-sublime-babel-tags": "javascriptreact",
        "isml": "html"
    },
    "emmet.triggerExpansionOnTab": true,
    "emmet.showExpandedAbbreviation": "never",
    "git.autofetch": true,
    "window.zoomLevel": 0,
    "[java]": {},
    "python.jediEnabled": false,
    "editor.fontSize": 12.5,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[scss]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.matchBrackets": false,
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "vsicons.dontShowNewVersionMessage": true,
    "[php]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    }
}
```
**Workspace settings :**
```
	"settings": {
		"search.exclude": {
			"**/static/default/js": true,
			"**/static/default/css": true,
			"**/test": true,
		},
		"extension.prophet.upload.enabled": true,
		"extension.prophet.clean.on.start": false,
		"files.exclude": {
			"**/.classpath": true,
			"**/.settings": true,
			"**/.factorypath": true
		},
		"beautify.ignore": "**/client/**/*.js",
		"eslint.autoFixOnSave": true,
		"javascript.format.enable": false
	},
``` 

I don't have any `.htmlhintrc` file. 

Thanks.

**Comment by SqrTT** [comment] 2019-10-01 10:23
Looks like formater is reason for such behavior. Could you please disable `formatOnSave` as workaround?

**Comment by rmkpatchaa-sfdc** [comment] 2019-10-01 10:40
Yes the formater is the reason.
When I disabled the formatOnSave I don't have the problem anymore. But as soon as I format the file manually, the CPU goes up again.

**Comment by SqrTT** [comment] 2019-10-01 10:45
the issue should be fixed in v1.2.1, 
could you please check and confirm it works for you?

**Comment by tonygustafsson** [comment] 2019-10-01 11:21
OMG it seems to work for me. Thanks a lot - this really makes SFCC development easier for me. Great fetch with the formatter.

**Comment by rmkpatchaa-sfdc** [comment] 2019-10-01 12:29
👍 This is awesome... Thanks a lot.

**Closed** 2019-10-01 12:56 UTC
