### ISSUE TITLE
Error: Internal Server Error on MAP object

### ISSUE THREAD

**Issue by julienphilippe** [SqrTT/prophet#148] opened 2018-11-26 07:52 UTC
Your plugin working great, but when i reinstall my computer last week, i got this issue. 

When I open Map object, the debug console display this : 
waiting for breakpoint hit...
Error: Internal Server Error
 Error: Internal Server Error
    at Request.request [as _callback] (c:\Users\jphilippe\.vscode\extensions\sqrtt.prophet-1.0.21\out\Connection.js:57:35)
    at Request.self.callback (c:\Users\****\.vscode\extensions\sqrtt.prophet-1.0.21\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (c:\Users\****\.vscode\extensions\sqrtt.prophet-1.0.21\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (c:\Users\****\.vscode\extensions\sqrtt.prophet-1.0.21\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

and the variables values did not change anymore. Any clue ? 
thx

**Comment by julienphilippe** [comment] 2018-12-11 09:50
yes duplicate

**Comment by julienphilippe** [comment] 2018-12-11 11:52
![beforecrash](https://user-images.githubusercontent.com/43367535/49798872-a0f75500-fd43-11e8-9682-81fba8dad45b.png)
![afterbeforecrash](https://user-images.githubusercontent.com/43367535/49798873-a359af00-fd43-11e8-9280-6cb3acfd931a.png)

screenshot attached

**Comment by SqrTT** [comment] 2019-02-08 10:20
closing as duplicate of #95 (tracking there)

**Closed by SqrTT** 2019-02-08 10:20 UTC
