### ISSUE TITLE
Debugger not starts up (with no errors or messages)

### ISSUE THREAD

**Issue by vrushali-desai** [SqrTT/prophet#206] opened 2019-11-29 15:30 UTC
Prophet Debugger is not working for me as expected since past few days. When I click on the run I always get a popup asking to select the environment (screenshot attached below). Nothing happens after selecting the environment.

![Screenshot 2019-11-29 at 16 24 43](https://user-images.githubusercontent.com/17403653/69878320-e8fce800-12c4-11ea-93e5-32505595f086.png)

It was working fine before. I have tried also by disabling other extensions, closing VSCode completely but nothing seems to help. The debugger **sometimes** works properly after I reboot the system. I am on

 - OS: macOS Catalina
 - VSCode version - 1.40.2
 - The extension version - 1.2.4

**Comment by ctwh** [comment] 2019-12-05 20:35
Experiencing same problem.  @SqrTT any updates?  I think currently I am relegated to using Eclipse when needing to debug.

**Comment by SqrTT** [comment] 2019-12-06 08:37
I'm not able to reproduce. Could you guys provide more detailed info/steps? 
Is the issue reproducible for older versions? Any logs/errors? Try to reinstall the extension.

**Comment by vrushali-desai** [comment] 2019-12-06 09:54
Strangely the debugger is working for me now. Although I cannot say for sure what fixed the debugger; but one thing is that now it's started working after I save my projects in workspace.  Of course I had tried it before  also but had not worked; also I could use the debugger previously without having a workspace and yes, had done the reinstallation of the extension several times  before posting the issue.
Nevertheless, I am happy that it's working for me now as even I was considering moving to eclipse to be able to debug.

**Comment by isabelklings** [comment] 2019-12-06 10:35
I still have this issue. Debug console error message:

```Error
 Error
    at Request._callback (###\.vscode\extensions\sqrtt.prophet-1.2.4\out\Connection.js:73:35)
    at Request.self.callback (###\.vscode\extensions\sqrtt.prophet-1.2.4\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (###\.vscode\extensions\sqrtt.prophet-1.2.4\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (###\.vscode\extensions\sqrtt.prophet-1.2.4\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)Disconnecting...
Error```

I installed previous VS Code version, previous Prophet version, I created a new workspace and I had no success.

**Comment by SqrTT** [comment] 2019-12-18 11:52
could you please try to uncheck extension.prophet.sandbox.filesystem.enabled = false

![image](https://user-images.githubusercontent.com/1271300/71084249-89944880-219d-11ea-8694-30c8abc2e85a.png)

and remove Sandbox File system workspace, and see if debugger works after that?

**Comment by isabelklings** [comment] 2020-01-02 12:45
> could you please try to uncheck extension.prophet.sandbox.filesystem.enabled = false
> 
> ![image](https://user-images.githubusercontent.com/1271300/71084249-89944880-219d-11ea-8694-30c8abc2e85a.png)
> 
> and remove Sandbox File system workspace, and see if debugger works after that?

Unfortunately it's not working :( Do you have another idea maybe? Thank you!

**Comment by ctwh** [comment] 2020-01-02 19:35
@SqrTT That seemed to work for me.

**Comment by bradbrock** [comment] 2020-01-07 21:06
I'm also experiencing the issue. setting `extension.prophet.sandbox.filesystem.enabled=false` did not resolve the problem.

**Comment by SqrTT** [comment] 2020-01-13 09:23
@bradbrock 
Have you tried to remove Sandbox File system workspace?

![image](https://user-images.githubusercontent.com/1271300/72244534-28726000-35f7-11ea-866b-459e69247984.png)

**Comment by bradbrock** [comment] 2020-01-18 22:01
@SqrTT I haven't, but the issue seems to have worked itself out. My sandbox was restarted from control center and everything has been working as expected since then.

**Comment by sghata** [comment] 2020-02-06 18:23
I'm also experiencing the same issue. The debugger stops working, and I get the following:
![image](https://user-images.githubusercontent.com/19668725/73965955-b7168c00-48da-11ea-94f9-a24d7cb848fc.png)
even though I have the launch.json file.
When I hit "create a launch.json file", I get the following error:

> Unable to create 'launch.json' file inside the '.vscode' folder (Unable to write file (EntryNotFound (FileSystemError): ccfs://current-sandbox/.vscode)).

The way I'm currently fixing it is by uninstalling prophet, restarting vscode, and then installing it again.
The issue seems to happens once every few days but I've not seen a pattern or a way to reproduce it.

**Comment by SqrTT** [comment] 2020-02-07 09:13
@sghata 
Have you tried to disable sandbox filesystem and remove it from workspace, like described above?

**Comment by cgornez** [comment] 2020-02-11 05:59
Hi, 
I am also experiencing this today.
![image](https://user-images.githubusercontent.com/50477775/74213979-836ea400-4cd6-11ea-8237-90944448ac5e.png)

I've already disabled the sandbox filesystem but it's not working for me.

**Comment by SqrTT** [comment] 2020-03-10 09:09
Hello all.

This ticket has 3 totally different issues:

1. debugger doesn't start with no error (or messages) in debug console.
2. Can't create configuration `launch.json` (Unable to write file (EntryNotFound (FileSystemError): ccfs://current-sandbox/.vscode)).
3. debugger starts with error in debug console.

So, let's process as different issues.
1. Unfortunately, I'm not able reproduce an issue, need more details, log, etc.  
2. remove sandbox file system should help.
3. let's track in #224

**Comment by jmatos** [comment] 2020-04-21 15:54
I'm also having the issue with the debugger not working - no error message at all.  In vscode I notice that the progress animation that appears when you click on the Run arrow or press F5 never stops.  Is there a way to see what is going on via logs?

**Comment by SqrTT** [comment] 2020-04-21 17:26
do you have installed a plugin LiveSearch? like in #147 ?

**Comment by SqrTT** [comment] 2020-04-21 17:28
is issue reproducible if all other plugins are disabled?

**Comment by jmatos** [comment] 2020-04-21 23:09
I disabled all plugins and I'm still not able to debug :(

**Comment by jmatos** [comment] 2020-04-22 04:05
I got it working again - I disabled the Prophet extension and then enabled it but this time I chose the "Enable (Workspace)" option instead of "Enable" - not sure why this made a difference but I'm happy now!
![Screen Shot 2020-04-21 at 11 02 32 PM](https://user-images.githubusercontent.com/129402/79939384-96af9580-8424-11ea-8877-8e2fb5e227bd.png)

**Comment by jmatos** [comment] 2020-04-22 04:41
I spoke too soon - its not working again :(

**Comment by jmatos** [comment] 2020-04-23 22:04
Any other ideas?  The debugging feature in eclipse does work for me - that seems to indicate that it is an issue with the plugin or with vscode.  Am I the only one using a MAC that is having issues with debugging?

**Comment by jmatos** [comment] 2020-04-24 03:51
I guess its back to eclipse :(

**Comment by jmatos** [comment] 2020-04-24 04:06
Uninstalled vscode and installed vscode insiders and now debugging is working again.

https://code.visualstudio.com/insiders/

**Comment by SqrTT** [comment] 2020-05-24 13:12
vscode and vscode insiders use the same version of the extension...

**Comment by ValentinGurkov** [comment] 2020-11-19 09:41
For me, restarts of VSCode have always fixed the debugger not starting. I'm not sure this problem is related to the extension.

**Comment by vlad-simion** [comment] 2021-04-02 06:50
The debugger is not stopping the code on breakpoints without any error.
After restarting the VS multiple times debugger works but then the auto-upload is not working anymore. I need to use the command Enable Upload for any change.

OS: macOS Catalina
VSCode version - 1.54.3
The extension version - 1.4.15

**Comment by SqrTT** [comment] 2021-04-02 10:33
Hi @vlad-simion 
How long this is happening? Does it happen with previous versions? 
Could you please try to previous version?
Are you sure code is executed where breakpoints is set?
Let's say if add loging to file log records appears?

PS. seems you issue is not related to current ticket. Would be nice to not mix all issue into one.

**Comment by vlad-simion** [comment] 2021-04-07 05:41
> Hi @vlad-simion
> How long this is happening? Does it happen with previous versions?
> Could you please try to previous version?
> Are you sure code is executed where breakpoints is set?
> Let's say if add loging to file does log records appears?
> Is cache enabled on sandbox?
> 
> PS. seems you issue is not related to current ticket. Would be nice to not mix all issue into one and report it as separate

I found my issue. It looks like a git repository inside a cartridge broke the Prophet.
Once I removed the repository files the Prophet worked again as expected.

**Comment by basitafzal-omnicom** [comment] 2021-04-24 13:09
I had the same issue "debugger tries to initiate but goes away".
The reason behind this was my outdated credentials in `dw.json` file. 
It wasn't any issue with the VS Code or Prophet Debugger. Just sharing if it could help anyone else as well.

**Comment by suaterken** [comment] 2021-09-14 15:10
I have just experienced the same today, it appears it was my email. The email was correct but it requires case sensitive.
🔴 suat.erken@...
🟢 Suat.Erken@...
Weird because even though we use account manager, some projects accept the lower case, some of them require camel case. maybe it would fix for someone as well.

**Comment by vinodshettyhn** [comment] 2021-11-16 21:39
Hi @SqrTT , I am facing some issue while debugging. It does not go to the next breakpoint. It always gives (undefined Please restart debugger). Please find the attached screenshot for reference:- 
<img width="1218" alt="Screenshot 2021-11-17 at 3 08 27 AM" src="https://user-images.githubusercontent.com/42642738/142069992-446d90a9-5941-43ae-815d-73dcafa08112.png">

**Comment by yashrajthakur1** [comment] 2022-03-23 09:25
@SqrTT I'm unable to debug the code, I tried all possible ways which is mentioned in the group.
ext prophet upload is working fine for code deployment but for debugging, it's not working. Attached ref an Image
<img width="956" alt="image" src="https://user-images.githubusercontent.com/87060237/159666539-98900c15-79f6-4bd9-86f4-cf57a4492f15.png">

**Comment by crisoncode** [comment] 2023-02-20 08:29
> do you have installed a plugin ~LiveSearch~ LiveShare ? like in #147 ?

did you find a solution for that? Liveshare is a must for work in pair programming and right now we can't use the debugger in live share sessions

**Comment by SqrTT** [comment] 2023-04-10 10:59
seems the issue collects more and more non related staff. So closing

**Closed by SqrTT** 2023-04-10 10:59 UTC

**Comment by Renan-Costa-Sousa** [comment] 2023-05-29 16:36
I am having the same issue as described in the first post. The debugger won't start, no error messages anywhere.
Tried enabling for workspace, reopening the folder, reinstalling, nothing works.

**Comment by kriskw1999** [comment] 2023-06-19 12:02
I solved a similar kind of issue with Salesforce by downgrading the extension version to 1.4.30.
I had the debugger in vscode that was starting without any error message or something readable and with a lower version works perfectly.
