### ISSUE TITLE
isscript formatting

### ISSUE THREAD

**Issue by z1haze** [SqrTT/prophet#97] opened 2018-03-28 20:04 UTC
Hi, I am new to vscode in general, so I apologize if I've missed something, but I am using your extension, and I am unable to get isscript content to format like i'd expect javascript to.

**Comment by SqrTT** [comment] 2018-03-29 08:41
the extention is unable to format `isscript`. Potentially I could force VSCode to consider `isscript` as `javascript` but problem there is that `isscript` isn't javascript (since may include info about types).

PS.
Moreover by best practice you should avoid using `isscript` in templates (avoid usage of buisness logic in templates).

**Comment by z1haze** [comment] 2018-03-29 13:37
Yep, I'm completely aware it's sort of frowned upon and I don't disagree, however there are some situations where it's just unavoidable, or would be way too much investment to extract to a script file. 
That being said, my primary editor is webstorm by jerbrains and I have done just that using it. I force isscript to format and syntax highlight like JavaScript. Would you consider making this change, I don't see it causing any more issues than. It having any formatting at all. You may be able to force it to typescript as well?


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Anatolii Obitskyi <notifications@github.com> Date: 3/29/18  4:41 AM  (GMT-05:00) To: SqrTT/prophet <prophet@noreply.github.com> Cc: Stephen Hendricks <stephen.hendricks87@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SqrTT/prophet] isscript formatting (#97) 
the extention is unable to format isscript. Potentially I could force VSCode to consider isscript as javascript but problem there is that isscript isn't javascript (since may include info about types).
PS.

Moreover by best practice you should avoid using isscript in templates (avoid usage of buisness logic in templates).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SqrTT/prophet","title":"SqrTT/prophet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SqrTT/prophet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SqrTT in #97: the extention is unable to format `isscript`. Potentially I could force VSCode to consider `isscript` as `javascript` but problem there is that `isscript` isn't javascript (since may include info about types).\r\n\r\nPS.\r\nMoreover by best practice you should avoid using `isscript` in templates (avoid usage of buisness logic in templates)."}],"action":{"name":"View Issue","url":"https://github.com/SqrTT/prophet/issues/97#issuecomment-377165701"}}}

**Comment by SqrTT** [comment] 2018-09-11 09:43
Hi @z1haze 
version 1.0.15 should be able to format `isscript` and placeholders `${ }` ... 
could you please check if it works for you? 

Thank you.

**Comment by kitsune-development** [comment] 2018-09-11 17:15
@SqrTT This is confirmed -- excellent work, thank you for the update!

**Comment by SqrTT** [comment] 2018-09-12 07:41
closing. implemented

**Closed by SqrTT** 2018-09-12 07:41 UTC
Labels: enhancement

**Comment by EvilJordan** [comment] 2019-09-17 20:36
General question, but specific to this issue:
even though `isscript` tags are discouraged use in isml templates, SFRA makes extensive use of them out of the box, thereby throwing lots of "problems" in the extension output. How can one disable this particular "problem" alert?

**Comment by SqrTT** [comment] 2019-09-20 09:50
`isscript` is used in SFRA only as exclusion for adding assets to page.

Warning can be disabled via `.htmlhint` file. (setup `tags-check` option) https://github.com/SqrTT/prophet/blob/master/src/server/langServer/services/ismlLinting.ts#L84
