### ISSUE TITLE
Dubug 500 error

### ISSUE THREAD

**Issue by mattyoungus** [SqrTT/prophet#247] opened 2020-08-12 14:20 UTC
Debugger will not connect. I can upload cartridges, but when trying to debug SFCC sandbox, the debugger will not connect. Yesterday, the debugger worked fine. Today, in the debug console in VS Code, I see this:

500
 undefinedDisconnecting...

In sandbox error logs, I see this:

ERROR RepeatedMessageSuppressingFilter-Thread com.demandware.core.script.dapi.DebuggerServlet Sites-Site JOB 93351766e7 12f2fd4ebc9693c212ce6f8c07 1156546413817428992 - The following message was generated more than 10 times within the last 180 seconds. It will be suppressed for 180 seconds: Failed to process request '/servlet/s/-/dw/debugger/v2_0/client', responding HTTP 500 INTERNAL_SERVER_ERROR fault message

**To Reproduce**
Open VS Code, try to start debugger.

Latest version of VS Code, extension, and iOS.

**Comment by SqrTT** [comment] 2020-08-12 17:09
hi.
Is this duplicate of #239 ?
Please double check your login.
https://github.com/SqrTT/prophet/issues/239#issuecomment-644512665

**Comment by SqrTT** [comment] 2020-08-17 08:21
if suggestion from comments doesn't solve your issue, feel free to reopen

**Closed by SqrTT** 2020-08-17 08:21 UTC
