### ISSUE TITLE
 aria-describedby attribute warning

### ISSUE THREAD

**Issue by foegit** [SqrTT/prophet#333] opened 2022-09-15 13:08 UTC
**Describe the bug**
 Prophet reports aria-describedby value as invalid which is not true. The type of this attribute must be string

**To Reproduce**
1. Go to any template with aria-describedby attribute
2. See warning that says "Aria attribute "aria-describedby" have invalid value. Valid values are 'true', 'false'".

**Expected behavior**
Wanrning is not shown

**Screenshots**
![image](https://user-images.githubusercontent.com/32361896/190410924-72eedf30-af9c-440a-861d-aa09b288e62e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode versionL: 1.71.0
 - The extension version 1.4.30

**Additional context**
The SRFA architecture makes extensive use of this attribute, so it's unfortunate that it's being misreported

**Comment by SqrTT** [comment] 2022-09-15 13:58
Hi @foegit 
Thank you for reporting. Indeed there are issue with this attribute. It will be fixed in next release.

**Comment by SqrTT** [comment] 2022-09-16 07:31
@foegit 
I would be appreciate if you may confirm if the issue is fixed in `1.4.31`

**Comment by foegit** [comment] 2022-09-16 08:00
Hi @SqrTT, the issue is fixed now! Thanks for the quick fix 💪

**Closed** 2022-09-16 08:11 UTC
