### ISSUE TITLE
Upload doesn't work for an instance that requires a 2-factor auth (certificates)

### ISSUE THREAD

**Issue by StefanvanderHeide** [SqrTT/prophet#270] opened 2021-02-11 10:35 UTC
I try to upload my code to my staging instance. But it gives an forbidden error.
I also saw that someone had the same problem in 2018. By then Prophet didn't have the 2 factor auth feature.
My question is if Prophet supports 2 factor auth certificates by now, and if so, how to use it.

**Comment by SqrTT** [comment] 2021-02-11 11:32
prophet does not support upload to staging/production and other instances that require certificates. There already exist issue for this #99. Let's track progress there.

PS. Probably you may use different tool to upload code to PIDs (DEV/STG) like Jenkins or other tools based on BuildSuite.

**Comment by SqrTT** [comment] 2021-02-19 09:27
closing since this is a duplicate of #99

**Closed** 2021-02-19 09:27 UTC
