### ISSUE TITLE
 the debug starts and then breaks off.

### ISSUE THREAD

**Issue by Kammel-Heib** [SqrTT/prophet#341] opened 2022-12-08 10:31 UTC
hello I have the problem, the debug starts and then breaks off. the debug console protects me this .
`Unauthorized
 undefinedDisconnecting...
Unauthorized`

the launch.json is correct, workspace is set correctly.

the Prophet works fine

![Capture](https://user-images.githubusercontent.com/36574166/206424279-25c35ed8-0ac2-4c12-891f-cee177b0d150.JPG)

**Comment by lisunovdv** [comment] 2022-12-08 14:44
Have you tried to restart your sandbox?

**Comment by SqrTT** [comment] 2022-12-12 10:07
please double check your credentials, username is case sensitive for debugger. probably duplicate of #313

**Comment by Kammel-Heib** [comment] 2022-12-12 11:01
restart didn't help

**Comment by SqrTT** [comment] 2022-12-29 10:12
Hi @Kammel-Heib 
Did you have change to verify steps from the issue #313?

**Comment by SqrTT** [comment] 2023-01-17 13:55
@Kammel-Heib 
Is your issue been fixed?

**Closed as completed** 2023-02-10 15:32 UTC
