### ISSUE TITLE
Paste Issues

### ISSUE THREAD

**Issue by dlferro** [SqrTT/prophet#156] opened 2019-02-14 20:45 UTC
Attempting to paste text into an isml file I seem to get some extra spacing(1-2 tabs worth). I've tried toggling other linters and htmlhint from this package, but I'm still running into the issue.

**Comment by SqrTT** [comment] 2019-03-01 16:05
Could you please add some examples, so I can reproduce this thing?

**Comment by dlferro** [comment] 2019-03-01 16:11
I've actually gotten around it by turning off format on paste in vscode. Going to close for now.

**Comment by dlferro** [comment] 2019-06-17 02:34
@SqrTT I'm going to reprise this issue. Here's a quick video of modifying the suggestions.isml file.
https://drive.google.com/file/d/1GH3Mz0aIzafX4HJyjIBzRxuWOiKnAGZ3/view?usp=sharing let me know if there's anything else that might help you identify what would cause this.

**Comment by dlferro** [comment] 2019-07-10 14:44
@SqrTT do you have any recommendations for how I might be able to determine what is causing this?

**Comment by SqrTT** [comment] 2020-02-20 09:50
@dlferro 
This is happening because incorrect calculation of indentation in case line already has content.

Let's close this issue and track it in #221.

**Closed by SqrTT** 2020-02-20 09:50 UTC
