### ISSUE TITLE
Error - Unhandled method workspace/symbol

### ISSUE THREAD

**Issue by maxjf1** [SqrTT/prophet#242] opened 2020-07-10 16:55 UTC
**Describe the bug**
A random error message appeared 

```js
isml server init...[{"uri":"file:///home/maxjf1/projetos/capgemini/havaianas","name":"havaianas"},{"uri":"ccfs://current-sandbox/","name":"Sandbox - FileSystem"}]
htmlhint enabled
Finding files with custom tags... 
Finding templates... 
Found files --["/home/maxjf1/projetos/capgemini/havaianas/cartridges/app_havaianas_base/cartridge/templates/default/components/modules.isml","/home/maxjf1/projetos/capgemini/havaianas/cartridges/app_storefront_base/cartridge/templates/default/components/modules.isml"]
[Error - 13:46:04] Request workspace/symbol failed.
  Message: Unhandled method workspace/symbol
  Code: -32601 
```

**To Reproduce**
Unfortunally, IDK

**Screenshot**
![image](https://user-images.githubusercontent.com/6114888/87179404-124b1100-c2b5-11ea-9f4c-426c914304e0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - VSCode version 1.46.1
 - The extension version v1.3.19

**Additional context**
A popup appeared and showed the error

**Comment by SqrTT** [comment] 2020-07-14 07:01
Hi @maxjf1 
I appreciate, for reporting. From my site I also can't reproduce the issue. Most likely it's related to some specific templates. Could you monitor which templates are opened at moment of error, please?

**Comment by SqrTT** [comment] 2020-07-14 07:10
could you monitor v1.3.20 for the issue, please?

**Comment by SqrTT** [comment] 2020-08-14 09:13
closing for now, if still actual reopen, please

**Closed by SqrTT** 2020-08-14 09:13 UTC
