### ISSUE TITLE
Uploading breaks at the last cartridge upon init

### ISSUE THREAD

**Issue by marianbida** [SqrTT/prophet#72] opened 2017-12-14 11:41 UTC
When initially start uploading the cartridges, it breaks at deleting the last cartridge zip from remote.
[int_test] Deleting remote zip...
The upload process is restarting and it breaks again and again and again.

**Comment by SqrTT** [comment] 2018-01-15 11:44
Could you please add more details, so I am able to reproduce?

For example, a hierarchy of folders and example of dw.json.

**Comment by SqrTT** [comment] 2018-02-27 09:36
closing since no further info.

@marianbida feel free to reopen once you got more details

**Closed by SqrTT** 2018-02-27 09:36 UTC
