### ISSUE TITLE
Uploader - zip files not found

### ISSUE THREAD

**Issue by dwanczowski** [SqrTT/prophet#165] opened 2019-04-02 13:00 UTC
No matter what I do, I cannot get the clean/upload all working. Just stopped out of the blue. May be an issue only on my end, but any help would be appreciated! Thanks!
Even in a fresh code version - I'm receiving these errors and no cartridges are uploaded. I've tried uninstalling/reinstalling, removing all other extensions, etc. If it was a code version that had all the cartridges, they all get wiped out.
```
Warn: Current code version is "version1" while uploading is processed into "version3"

Current active version is: version1
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting local zip
[app_storefront_base] Zipping
[int_google] Deleting local zip
[int_google] Zipping
[modules] Deleting local zip
[modules] Zipping
[plugin_instorepickup] Deleting local zip
[plugin_instorepickup] Zipping
[modules] Deleting remote zip
[int_google] Deleting remote zip
[plugin_instorepickup] Deleting remote zip 
Error: Error: Not Found
Error: Error: Not Found 
	at Request.request [as _callback] (/Users/dwanczowski/.vscode/extensions/sqrtt.prophet-1.0.18/out/server/WebDav.js:15:36)
	at Request.self.callback (/Users/dwanczowski/.vscode/extensions/sqrtt.prophet-1.0.18/node_modules/request/request.js:185:22)
	at emitTwo (events.js:126:13)
	at Request.emit (events.js:214:7)
	at Request.<anonymous> (/Users/dwanczowski/.vscode/extensions/sqrtt.prophet-1.0.18/node_modules/request/request.js:1161:10)
	at emitOne (events.js:116:13)
	at Request.emit (events.js:211:7)
	at IncomingMessage.<anonymous> (/Users/dwanczowski/.vscode/extensions/sqrtt.prophet-1.0.18/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:313:30)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by SqrTT** [comment] 2019-04-02 13:12
duplicate of #157 ?

PS. please install fresh version of vscode to be able install `v.1.1.2` of extension.

**Comment by dwanczowski** [comment] 2019-04-02 13:43
Worked - thank you!

**Closed** 2019-04-02 13:45 UTC
