### ISSUE TITLE
Unable to set breakpoint to non backend file

### ISSUE THREAD

**Issue by nicowernli** [SqrTT/prophet#58] opened 2017-09-20 09:42 UTC
This is weird, I really don't know how to reproduce this error, but when trying to set a breakpoint in some files I get this error `Unable to set breakpoint to non backend file`. 

I'll add more information if I find out how to replicate.

**Comment by SGD1953** [comment] 2017-09-20 11:24
I got this too the other day, don't really have any more insights but it is not just you.

**Comment by SqrTT** [comment] 2017-09-20 15:29
[This](https://github.com/SqrTT/prophet/blob/master/src/mockDebug.ts#L169-L172) conditions must fit to set brackpoint

**Comment by SqrTT** [comment] 2017-11-09 00:03
Hi @nicowernli 
Is there known steps to reproduce?

**Comment by SqrTT** [comment] 2017-11-13 22:42
Didn't find reproduce the issue. Are you sure that was in backend file?

**Comment by SqrTT** [comment] 2018-01-11 18:59
closing since didn't know how to reproduce

**Closed by SqrTT** 2018-01-11 18:59 UTC
