### ISSUE TITLE
ISML server error on git diff

### ISSUE THREAD

**Issue by ufnd** [SqrTT/prophet#17] opened 2017-06-07 07:39 UTC
When you click to see in GIT difference you will get this error:

`onDocumentLinks {"textDocument":{"uri":"git:/d%3A/Code/app_storefront_core_ext/cartridge/templates/default/product/pt_productdetails.isml?%7B%22path%22%3A%22d%3A%5C%5CCode%5C%5Cecom-fatface%5C%5Capp_storefront_core_ext%5C%5Ccartridge%5C%5Ctemplates%5C%5Cdefault%5C%5Cproduct%5C%5Cpt_productdetails.isml%22%2C%22ref%22%3A%22~%22%7D"}}
`
`
[Error - 10:36:56] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Wrong scheme
  Code: -32603
`

**Comment by SqrTT** [comment] 2017-06-07 23:01
Hi @ufnd, 
thanks for raising an issue. 

The issue is addressed in v.0.5.2. Could you please confirm that is fixed for you?

**Comment by ufnd** [comment] 2017-06-08 09:54
Hi @SqrTT,
It's working now! Thanks a lot!
But I have some messages with warning - is it ok?

Example:
```
onDocumentLinks {"textDocument":{"uri":"git:/d%3A/Code/app_storefront_core_ext/cartridge/templates/default/product/productcontent.isml?%7B%22path%22%3A%22d%3A%5C%5CCode%5C%5Cecom-fatface%5C%5Capp_storefront_core_ext%5C%5Ccartridge%5C%5Ctemplates%5C%5Cdefault%5C%5Cproduct%5C%5Cproductcontent.isml%22%2C%22ref%22%3A%22~%22%7D"}}
[Warn  - 12:51:59] Unable to handle a "git" scheme
```

**Comment by SqrTT** [comment] 2017-06-08 10:11
yes, that intentionally.

**Closed by SqrTT** 2017-06-08 10:11 UTC
