### ISSUE TITLE
Error on watching multiple sub-directories

### ISSUE THREAD

**Issue by valterlima** [SqrTT/prophet#70] opened 2017-11-30 13:47 UTC
Hello,

Thanks and congratulations for the plugin, it's a really great tool :)

I'm having a issue when I have a dw.json like this:

> "cartridge": [
>     "xxxxxxxx/abcd",
>     "sitegenesis/app_storefront_core",
>     "sitegenesis/app_storefront_controllers"
> ]

Every time I change some code from either directory, Prophet tries to do a re-upload everything. Example:
`
[U 10:33:27] c:\projects\xxxxxxxx\abcd\file.js
`
`
Trying to re-upload
`
`
Start uploading cartridges
`

I know this isn't the correct configuration for the paths as indicated in the plugin description, but it's 
very useful when we have multiple GIT repositories

I'm using the latest version from the Plugin and VS Code in Windows 10.

Best regards,

**Comment by SqrTT** [comment] 2017-11-30 13:59
Hi.
Isn't this issue a duplicate of #55?

**Comment by valterlima** [comment] 2017-11-30 16:00
They are similar, but I detected that the error occurs when we have one more nested directory. With dwupload we have a similar issue as well.

**Comment by SqrTT** [comment] 2017-12-04 11:18
ahh, I see. Workaround for this issue could be a usage of symlinks ( #62 ).

The correct way would be to use [multiroot workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) but currently, the extension doesn't support it.

**Comment by CarolMinichOSF** [comment] 2017-12-11 14:02
will the extension support multiroot workspaces in the near future ? we sometimes have to make 50+ symlinks .. Thanks

**Comment by SqrTT** [comment] 2017-12-11 14:13
Yes, there are plans to add multiroot workspaces and SDAPI v2. Currently, I don't have a much time for the extension. I'm planning to do so in the first quarter of 2018.

**Comment by SqrTT** [comment] 2018-03-20 09:41
the multiroot has been added in `v1.0.0`

**Closed** 2018-03-22 08:30 UTC
Labels: enhancement
