### ISSUE TITLE
Clean/upload doesn't work

### ISSUE THREAD

**Issue by c-ri** [SqrTT/prophet#157] opened 2019-03-06 09:03 UTC
On "clean/upload" action :

> Cleanup code version...
[deletes successfully all cartridges]
> Error: Error: Not Found 
> Error: Error: Not Found 
> 	at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (...\.vscode\extensions\sqrtt.prophet-1.1.0\out\server\WebDav.js:17:36)
> 	at Request.init.self.callback (...\.vscode\extensions\sqrtt.prophet-1.1.0\node_modules\request\request.js:185:22)
> 	at Request.emit (events.js:182:13)
> 	at Request.EventEmitter.emit (domain.js:442:20)
> 	at Request.<anonymous> (...\.vscode\extensions\sqrtt.prophet-1.1.0\node_modules\request\request.js:1161:10)
> 	at Request.emit (events.js:182:13)
> 	at Request.EventEmitter.emit (domain.js:442:20)
> 	at IncomingMessage.<anonymous> (...\.vscode\extensions\sqrtt.prophet-1.1.0\node_modules\request\request.js:1083:12)
> 	at Object.onceWrapper (events.js:273:13)
> 	at IncomingMessage.emit (events.js:187:15)
> 	at IncomingMessage.EventEmitter.emit (domain.js:442:20)
> 	at endReadableNT (_stream_readable.js:1090:12)
> 	at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by oilvier** [comment] 2019-03-06 09:37
Hi,

Same problem here...

**Comment by fishme** [comment] 2019-03-06 10:10
me too

**Comment by fishme** [comment] 2019-03-06 10:11
it also not working with older versions

**Comment by bldave** [comment] 2019-03-06 10:14
I have the same issue, interestingly I get this bug only on one project

**Comment by aduponchel** [comment] 2019-03-06 10:20
Same here, only for 1 projets. Maybe a realm is bugged ? POD44 ...

**Comment by bldave** [comment] 2019-03-06 10:40
POD56 here

**Comment by nyadavsf** [comment] 2019-03-06 11:08
Looks like SNI issue. Prophet needs to support SNI. Commerce cloud recently enabled SNI.

**Comment by trippel** [comment] 2019-03-06 11:12
Funnily, after cleaning the project with Eclipse the plugin seems to work again.

**Comment by aharas** [comment] 2019-03-06 11:14
@nyadavsf: SNI will be enabled "beginning April, 2019" if we are to believe the official communication from Salesforce.

**Comment by fishtoasty** [comment] 2019-03-06 11:24
Salesforce have confirmed that SNI update is scheduled for the April 1st and is yet to be deployed.

**Comment by aharas** [comment] 2019-03-06 11:27
And anyway, the "request" npm module that prophet is using is SNI-compatible (I checked).

**Comment by fishtoasty** [comment] 2019-03-06 11:32
The 19.3 preview update release was deployed yesterday.

19.3 Preview Update | Tuesday, March 5 | SIGs (all PODs)

**Comment by aharas** [comment] 2019-03-06 11:43
I have a sandbox with the latest version from yesterday (19.3.1.130) that is working.

**Comment by nyadavsf** [comment] 2019-03-06 11:59
Not working same issue 

	at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (/Users/nyadav/.vscode/extensions/sqrtt.prophet-1.1.0/out/server/WebDav.js:17:36)
	at Request.init.self.callback (/Users/nyadav/.vscode/extensions/sqrtt.prophet-1.1.0/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (/Users/nyadav/.vscode/extensions/sqrtt.prophet-1.1.0/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (/Users/nyadav/.vscode/extensions/sqrtt.prophet-1.1.0/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ivanKh13** [comment] 2019-03-06 12:12
**dwupload** works for me as an alternative decision.  To load all catridges include them in --cartridge parameter separated by comma

**Comment by SqrTT** [comment] 2019-03-06 12:28
Could you please add `  "debug" : true` into your `dw.json` and see if there additional details?

**Comment by SqrTT** [comment] 2019-03-06 12:33
this is not SNI since "clenup" requests are working

**Comment by mapolin** [comment] 2019-03-06 12:35
My debug output is this, if it helps at all...
`
Current active version is: version1
Start uploading cartridges
delete bm_deploy_cartridge.zip
Cleanup code version...
delete bm_deploy
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
request [object Object] [object Object]
get-response ###########################################
# Generated file, do not edit.
# Copyright (c) 2019 by Demandware, Inc.
###########################################
fileVersion=1
maxVersions=0
version1/1549629380296/1551872401962
siteGenesis/1549629377474/1489065255482
1.57.2//1551365377164
1.57.1//1551365074574
tests//1521555117133
SG2/1491398714235/1491400804067
tmg_fr_v3_dev/1484645227901/1487609565151
v3Evo_mazz/1480650462636/1480650098712
controller_dev/1461823021839/1461837203335
fitflop_dev/1457591041187/1457425691505
coty_dev/1457501410966/1456151536776
coty/1456147737263/1448870144392
fitflop/1444650855423/1444802323741
version9/1549532519595/1398253045599
# end of file marker
`

**Comment by Super-Fly** [comment] 2019-03-06 12:37
`
Cleanup code version...
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
request [object Object] [object Object]
get-response ###########################################
# Generated file, do not edit.
# Copyright (c) 2019 by Demandware, Inc.
###########################################
fileVersion=1
maxVersions=0
ASDA/1526578701778/1551865466896
CAE_New/1526578694555/1493707053333
tests//1521536505270
SG/1521020824294/1520846806055
version1/1517903561548/1517903569492
# end of file marker

**Comment by nyadavsf** [comment] 2019-03-06 12:37
Mine also same log. even cleanup is not working. it just shows in log but when it goes to delete it. It fails.

**Comment by bldave** [comment] 2019-03-06 12:46
Same log here

**Comment by ketsuo** [comment] 2019-03-06 13:09
me too...

**Comment by mapolin** [comment] 2019-03-06 14:31
The "Not Found" error throw is caused by this response, which is returned for a cartridge that the uploader deleted previously.
```
"DELETE /on/demandware.servlet/webdav/Sites/Cartridges/version1/bm_deploy HTTP/1.1"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>404 - URL Error</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>URL Not Found</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		The requested URL is invalid.
	</p>
	<hr>
</body>
</html>
```

**Comment by matthewrose** [comment] 2019-03-06 16:09
Just a note, downgrading to version 1.0.25 seems to fix the issue on Windows. If you upgraded to 1.1.0 on Mac, you might not be as easily able to downgrade based on reports I'm hearing. You may need to uninstall and delete all files related to the plug before installing the previous version.

**Comment by aboutvale** [comment] 2019-03-06 16:18
Same issue here

**Comment by AndreRSilva** [comment] 2019-03-06 16:24
I have the same issue

**Comment by rradu23** [comment] 2019-03-06 16:37
@matthewrose I downgraded to 1.0.25 on Mac but still not working...

**Comment by matthewrose** [comment] 2019-03-06 16:42
> @matthewrose I downgraded to 1.0.25 on Mac but still not working...

Like I said, it worked for me on Windows. On Mac you may need to delete some files related to the Prophet plugin on your local file system to get it working.

I have reports coming from Mac users that haven't upgraded to 1.1.0 that it is working for them.

**Comment by matthewrose** [comment] 2019-03-06 16:50
@SqrTT It's possible that the error is related to the change to WebDav.ts made here:

https://github.com/SqrTT/prophet/commit/667b9eb4d9a4ad58cc9f8aa8bb6acfb77b08ca61#diff-0a78b095cdd0b6f46d77c0361c0ca1d8

The error in the logs highlights this issue:

Error: Not Found
at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (....vscode\extensions\sqrtt.prophet-1.1.0\out\server\WebDav.js:17:36)

**Comment by juanpenarandaosf** [comment] 2019-03-06 16:55
Same problem here

**Comment by c-ri** [comment] 2019-03-06 17:00
Downgrading to 1.0.25 (and even 1.0.21) didn't work for me. I still get the same error.

**Comment by SqrTT** [comment] 2019-03-06 17:00
not sure if this is related to those change since then this will be not working for all.

cc @matthewrose

**Comment by matthewrose** [comment] 2019-03-06 17:55
@SqrTT 
I can confirm that I had the error yesterday with 1.1.0 and it works for me today after downgrading versions to 1.0.25. This was on the same instance (demo SIG instance) and code version for both tests. Here is the pattern I've found:

- Users who who have never upgraded to 1.1.0 are seeing no issues.
- After upgrading to 1.1.0 the issue starts happening on both Mac and Windows.
- Downgrading the version to 1.0.25 fixes the issue on Windows but Mac users continue to experience the issue.

**Comment by zlkahn** [comment] 2019-03-06 18:43
@SqrTT 
I also began having the issue yesterday, however downgrading has not resolved my issue.  This is almost certainly connected to SFCC Maintenance yesterday as it cutoff almost immediately in line with the reported maintenance email update time.
[screencapture-demandware-statuspage-io-incidents-htbt7l41ywm7-2019-03-06-12_42_47.pdf](https://github.com/SqrTT/prophet/files/2937801/screencapture-demandware-statuspage-io-incidents-htbt7l41ywm7-2019-03-06-12_42_47.pdf)

**Comment by TSchaufCanyon** [comment] 2019-03-07 07:07
You have to add a space in WebDav.js at Line 208 after 'Not Found':

208            if (err && err.message === 'Not Found ') {

**Comment by VladStanimirOSF** [comment] 2019-03-07 07:50
> You have to add a space in WebDav.js at Line 208 after 'Not Found':
> 
> 208 if (err && err.message === 'Not Found ') {

This actually works

**Comment by hnestmann** [comment] 2019-03-07 08:04
Nice Vlad - anyone objects if I provide this as a PR?
if (err && err.message && err.message.trim() === 'Not Found') {

**Comment by danielloader** [comment] 2019-03-07 09:00
PR seems merged: https://github.com/SqrTT/prophet/pull/159 just the waiting game until it's live now

**Comment by SqrTT** [comment] 2019-03-07 09:03
I've published changes. Could you please check and confirm if it works?

PS.
@mapolin thank you for PR

**Comment by ivanKh13** [comment] 2019-03-07 09:07
it works, thank you @SqrTT !!

**Comment by AndreRSilva** [comment] 2019-03-07 09:08
it's working for me! thanks! :)

**Comment by SqrTT** [comment] 2019-03-07 09:09
in that case feel free to reopen if you still have the issue in `v1.1.1`. So closing for now.

**Closed by SqrTT** 2019-03-07 09:09 UTC

**Comment by bhafenrichter** [comment] 2019-03-07 09:12
Works for me as well!

**Comment by JosVP** [comment] 2019-03-07 09:18
kudos for the quick fix!

**Comment by c-ri** [comment] 2019-03-07 09:57
It works great, many thanks for the quick fix :)

**Comment by juanpenarandaosf** [comment] 2019-03-08 13:51
You made my day! Thank you for the fix :)

**Comment by sapheria** [comment] 2019-03-27 05:59
I am currently having upload issue.
Today, it suddenly stopped working for uploading.

Could you guys check this again?

Here is the log you can refer to.
and then i am using newest prophet debugger 1.1.2 

`Error: Error: Not Found 
Error: Error: Not Found 
	at Request.request [as _callback] (/Users/wchoi/.vscode/extensions/sqrtt.prophet-1.0.12/out/server/WebDav.js:15:36)
	at Request.self.callback (/Users/wchoi/.vscode/extensions/sqrtt.prophet-1.0.12/node_modules/request/request.js:185:22)
	at emitTwo (events.js:126:13)
	at Request.emit (events.js:214:7)
	at Request.<anonymous> (/Users/wchoi/.vscode/extensions/sqrtt.prophet-1.0.12/node_modules/request/request.js:1161:10)
	at emitOne (events.js:116:13)
	at Request.emit (events.js:211:7)
	at IncomingMessage.<anonymous> (/Users/wchoi/.vscode/extensions/sqrtt.prophet-1.0.12/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:313:30)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by ShahzadHafeez** [comment] 2019-08-23 12:58
I have to upload my cartridges to an empty code version in SIG Instance. But the same issue has occurred.
I am using prophet debugger 1.0.22
 
@SqrTT 
**View > Open View > Output:**
Using config file 'c:\Users\..........\cartridges\dw.json'
Connection validated successfully
Current active version is: ver2
Start uploading cartridges
Cleanup code version...
[app_sitegenesis_controllers] Deleting local zip
[app_sitegenesis_controllers] Zipping
[app_sitegenesis_controllers] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: ver2
Start uploading cartridges
Cleanup code version...
[app_sitegenesis_controllers] Deleting local zip
[app_sitegenesis_controllers] Zipping
[app_sitegenesis_controllers] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: ver2
Start uploading cartridges
Cleanup code version...
[app_sitegenesis_controllers] Deleting local zip
[app_sitegenesis_controllers] Zipping
[app_sitegenesis_controllers] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: ver2
Start uploading cartridges
Cleanup code version...
[app_sitegenesis_controllers] Deleting local zip
[app_sitegenesis_controllers] Zipping
[app_sitegenesis_controllers] Deleting remote zip
Error: Error: Not Found 
Error: Error: Not Found 
    at Request.request [as _callback] (C:\Users\shahzad.hafeez\.vscode\extensions\sqrtt.prophet-1.0.22\out\server\WebDav.js:15:36)
    at Request.self.callback (C:\Users\shahzad.hafeez\.vscode\extensions\sqrtt.prophet-1.0.22\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\shahzad.hafeez\.vscode\extensions\sqrtt.prophet-1.0.22\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\shahzad.hafeez\.vscode\extensions\sqrtt.prophet-1.0.22\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
