### ISSUE TITLE
Optimise code upload for longer running builds

### ISSUE THREAD

**Issue by SGD1953** [SqrTT/prophet#187] opened 2019-09-19 11:55 UTC
Currently we wait for 300ms before we start uploading and we upload each resource one by one. This is great as long as the editor is used, however it is not so great when a build is happening which (re-)creates a lot of sources. The idea would be to collect changes by debouncing the events and only upload when there are no more file changes happening. This would allow the build to finish before the upload starts.

**Comment by SqrTT** [comment] 2019-09-19 12:29
Hi @SGD1953 
bit unclear: about what builds are you talking? and why in your build the same file is changed many times?

**Comment by SGD1953** [comment] 2019-09-19 12:59
If you generate CSS & JS using SASS, webpack etc. your build might create a `dist` folder which is removed at the beginning of the build and then it will incrementally add files. What I have experienced is that when the folder gets deleted, the extension will error out & start re-uploading all cartridges. The build however might still be running, so the zips uploaded are incomplete and then you have to upload again. I always found that a bit annoying when it happened to me.

**Comment by hnestmann** [comment] 2019-09-19 15:44
if you run webpack in the command line the uploader kicks in while still files are added to the static folder. If we reset the 300ms as a new change comes in we'd be able to catch such scenario immediately.

**Comment by SqrTT** [comment] 2019-10-01 09:52
we can't get rid of 300ms delay. It's required to allow tools to finish write (is there any other way to detect if writing to file is done?)

@SGD1953 why do you assume 300ms delay is reason of issue you are facing?

Still not see what exactly issue is? Could you please share logs or something?

**Comment by SGD1953** [comment] 2019-10-01 11:18
The ask is not to get rid of the delay, the ask is to defer uploading (for another 300m) until there is no further file change event. I create an experimental PR at https://github.com/SGD1953/prophet/pull/2/files

This if a build happens which bulk-creates & updates JS & CSS files the upload would wait until it is done.

**Comment by SqrTT** [comment] 2019-10-01 13:08
does it solves issue with recreation a `dist` folder?

**Comment by SqrTT** [comment] 2019-10-21 13:20
I've tried to target issue in v1.2.2, Could you check if issue is reproducible there, please?

**Comment by dmersiowsky** [comment] 2019-12-12 08:06
Unfortunately it's not solved yet (using v1.2.4). My recommendation would be to make the delay configurable so it can be adjusted per project.

Let me try to explain the enhancement in detail:

- "Building" the project is being triggered via Command line
- Sometimes the process takes quite some time, up to several minutes
- A lot of files get written during that process
- Prophet at first tries to "keep up" uploading files one-by-one
- At some it errors out and then triggers a clean/upload all
- However this happens while the build process is still running, so we'll have to trigger clean/upload all again after the build is finished because some files were missed

As @SGD1953 was suggesting, I would also recommend to add some kind of timer (with configurable amount of time), which is reset upon every file change that is detected. Once the timer finishes without an interruption, the clean/upload all can be triggered.

**Comment by SqrTT** [comment] 2020-02-10 09:04
Hi all, could anybody provide upload logs for this case?

We heed identify root case for this issue, seems to be there are network problems and in this case any delay/debounce/throttling would not help

**Comment by SqrTT** [comment] 2020-02-27 08:12
I've fixed small issue that may broke uploading during large files change.
 Could you please check if issue is actual in v1.2.27?

**Comment by SqrTT** [comment] 2020-04-17 08:37
not sure if issue is actual, closing for now. Feel free to reopen

**Closed by SqrTT** 2020-04-17 08:37 UTC
