### ISSUE TITLE
Weird Error In Prophet Uploader Log

### ISSUE THREAD

**Issue by AlexandruDinulescu** [SqrTT/prophet#93] opened 2018-03-23 09:41 UTC
Hello
After the initial upload I'm getting this in the error log and I wasn't getting it on a previous version.

Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: ACTIVE_VERSION
Upload cartridges on start is disabled via config // 
Watching files

As a side note, why aren't they uploading on start, I haven't changed anything in the settings recently. And I cant figure out where that setting is.

Thanks

**Comment by SqrTT** [comment] 2018-03-23 18:05
You should set `extension.prophet.clean.on.start` to `true` (if it's set to `false`),
More details about setting could be found here https://code.visualstudio.com/docs/getstarted/settings

also please provide more details form error log

**Comment by romssilva** [comment] 2018-03-26 19:06
I've been also having the same issue since the last update. I can't really provide specific steps to reproduce it since sometimes it will through that error and sometimes it won't. But it usually happens after a file change. One thing I've noticed is that the error only occurs on my Windows environment. macOS seems to be fine.  `extension.prophet.clean.on.start` is already set to `true`.

```
Error: Error: Method Not Allowed
Error: Error: Method Not Allowed
	at Request.request [as _callback] (C:\Users\path\.vscode\extensions\SqrTT.prophet-1.0.1\out\server\WebDav.js:15:36)
	at Request.self.callback (C:\Users\path\.vscode\extensions\SqrTT.prophet-1.0.1\node_modules\request\request.js:186:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (C:\Users\path\.vscode\extensions\SqrTT.prophet-1.0.1\node_modules\request\request.js:1163:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (C:\Users\path\.vscode\extensions\SqrTT.prophet-1.0.1\node_modules\request\request.js:1085:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
```

**Comment by ominestre** [comment] 2018-03-27 13:38
Experiencing the same issue on my Windows machine. I played around with the file watcher and modifying a single file seemed to go through fine. When I run a static resource build (multiple files deleted and rebuilt) I get the following error and the files get locked until I close VS Code:

```
Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: primary
Upload cartridges on start is disabled via config
Watching files
```

I confirmed that `extension.prophet.clean.on.start` is set to true.

**Comment by ominestre** [comment] 2018-03-28 13:19
Rebuilt my extension from a previous versions and [v0.10.4](https://github.com/SqrTT/prophet/commit/2a87a6e35920c9e5eff22078116304ce66e80848) is the last good point.

**Comment by SqrTT** [comment] 2018-03-28 17:03
Hi guys,
Could you please check if it works in `v1.0.2`?

**Comment by ominestre** [comment] 2018-03-28 17:47
Still running into the same issue with v1.0.2

**Comment by SqrTT** [comment] 2018-03-29 08:47
Could you please share a full log of uploading?

**Comment by romssilva** [comment] 2018-03-29 17:30
It looks the same.

`Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: my_version
Upload cartridges on start is disabled via config
Watching files`

As @ominestre mentioned, "modifying a single file seemed to go through fine. When I run a static resource build (multiple files deleted and rebuilt) I get the following error", same scenario here.

**Comment by ominestre** [comment] 2018-03-29 17:36
@SqrTT  Here is a log using v1.0.2 after running a build.

```
[D 13:21:22] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css
[C 13:21:23] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default
Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: primary
Upload cartridges on start is disabled via config
Watching files
[U 13:21:24] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\sass.css
[C 13:21:24] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css
[U 13:21:24] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\sass.css.map
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\globals.min.js
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\pdp.min.js
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\scripts.min.js
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\dynamic-header.min.js
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\checkout.min.js
[U 13:21:37] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\js\vendors.min.js
[U 13:21:39] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\sass.min.css
[U 13:21:39] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\sass.min.css.map
[C 13:21:39] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css
[U 13:21:39] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\dynamic-header.min.css.map
[U 13:21:39] c:\Users\myuser\repos\ecomm-dwre\cartridges\company_storefront\cartridge\static\default\css\dynamic-header.min.css
Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: primary
Upload cartridges on start is disabled via config
Watching files
```

**Comment by SqrTT** [comment] 2018-04-05 13:52
Hi guys,
Could you please check if it works in `v1.0.4`?

**Comment by SqrTT** [comment] 2018-04-05 13:55
the issue was on Windows it fires events for directory change (deleting and creating files) the extension tried upload directory and fails

**Comment by romssilva** [comment] 2018-04-05 17:49
Hi @SqrTT .

Seems to be fixed now. Thanks a lot.

**Closed** 2018-04-06 07:24 UTC
Labels: bug

**Comment by aagrawal26** [comment] 2020-04-21 18:34
I'm unable to get the ISML suggestion when Prophet Uploader is enabled. ctrl+space every time shows Loading... How to fix this issue?
