### ISSUE TITLE
VSC Debug console throwing the Internal Server Error

### ISSUE THREAD

**Issue by hbhupatiraju** [SqrTT/prophet#240] opened 2020-05-19 22:35 UTC
Please  help me with  the Issue I am facing.

Trying to enable the Debug in VSC and its throwing the below error using Prophet 1.3.4. The Prophet uploader  is working fine.

**To Reproduce**
1. Click on Run Debugger
2. selected Attach to Sandbox
3. Click on Start Debugging

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode - Insiders version 1.46.0,  VSCode Version 1.45.1
 - The extension version : Prophet Debugger v1.3.4

![image](https://user-images.githubusercontent.com/65237825/82385176-79f48680-99ff-11ea-86ec-15c91a4a61ae.png)

**Comment by SqrTT** [comment] 2020-05-20 07:20
hello @hbhupatiraju. Is this duplicate of #239 ?

**Comment by hbhupatiraju** [comment] 2020-05-20 13:33
> hello @hbhupatiraju. Is this duplicate of #239 ?

Hi, Yes you are right. Looks like #239 is the same issue. But none of the solutions provided there are working for me. I am able to upload the code and I am seeing my version in SFCC updated when I upload. Only issue is with the debugger throwing internal server error.

Thank you..

**Comment by hbhupatiraju** [comment] 2020-05-20 13:41
Also i have Admin Role setup for my user ID in SFCC. So there shouldn't be any access issues.

**Comment by SqrTT** [comment] 2020-05-24 13:00
let's track progress in #239

**Closed by SqrTT** 2020-05-24 13:00 UTC
