### ISSUE TITLE
Upload not working after latest VSCode update (v0.10.3)

### ISSUE THREAD

**Issue by chrisliott** [SqrTT/prophet#87] opened 2018-03-08 16:42 UTC
Uploader get stuck in clean:

Start uploading cartridges
Cleanup code version...
mode list

**Comment by SqrTT** [comment] 2018-03-09 13:19
Hi @chrisliott 
thank you for reporting, 
I'm not able to reproduce the issue. :(
Could you please add more details (especially how many cartridges do you have on the list)? 

PS. As temporary workaround you may set `extension.prophet.clean.up.code.version.mode` to `none`. This will disable cleaning sandbox before upload.

**Comment by chrisliott** [comment] 2018-03-09 18:25
Hey @SqrTT,

That seems to have been the problem. I didn't have any cartridges in my dw.json config. After adding the list, the clean works flawlessly!

The docs have the cartridges list marked as optional. Is this no longer the case?

Thanks,

Chris

**Comment by SqrTT** [comment] 2018-03-12 10:28
Hi @chrisliott,
the issue should be fixed in `v0.10.4`. Could you please confirm?

PS.
Correct. Cartridges list is optional. The last release has a small change with broken logic.

**Comment by chrisliott** [comment] 2018-03-12 14:59
Hey @SqrTT,

It is fixed for me after the update! Thank you for the quick turn around and for making this extension in the first place!

Thanks,

Chris

**Closed** 2018-03-12 15:23 UTC
Labels: bug
