### ISSUE TITLE
Cannot upload cartridges

### ISSUE THREAD

**Issue by flovero** [SqrTT/prophet#253] opened 2020-08-19 12:56 UTC
**Describe the bug** 
Upload doesn't work
**To Reproduce**
Select clean project/upload all:
Starting...
Error: TypeError: Cannot read property 'prototype' of undefined
Error: TypeError: Cannot read property 'prototype' of undefined
	at runInContext (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:11692:28)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:23294:11)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:23325:3)
	at Object.71./NPYxj (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:23327:4)
	at s (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:220)
	at eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:271)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:6326:9)
	at Object.53./NPYxj (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:6605:4)
	at s (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:220)
	at eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:271)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:6:12)
	at Object.1../progress (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:111:4)
	at s (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:220)
	at eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:271)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1138:12)
	at Object.8../ajax (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1297:4)
	at s (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:220)
	at eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:271)
	at Object.eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:124:14)
	at Object.2../captcha (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:333:4)
	at s (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:220)
	at e (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:391)
	at eval (eval at <anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241914), <anonymous>:1:409)
	at e._subscribe (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241969)
	at e._trySubscribe (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:4551)
	at e.subscribe (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:4337)
	at s (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:5628)
	at t._innerSub (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:179755)
	at t._tryNext (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:179630)
	at t._next (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:179453)
	at t.next (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:1085)
	at ReadStream.<anonymous> (/Users/francescolovero/.vscode/extensions/sqrtt.prophet-1.3.23/dist/extension.js:16:241663)
	at ReadStream.emit (events.js:203:13)
	at internal/fs/streams.js:224:14
	at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/graceful-fs.js:57:14
	at FSReqCallback.oncomplete (fs.js:153:23)

 - OS: Catalina 10.15.6
 - VSCode version Version: 1.48.0
 - The extension version 1.3.23

**Comment by SqrTT** [comment] 2020-08-20 14:28
unfortunately, I'm not able to reproduce the issue.

**Comment by SqrTT** [comment] 2020-09-16 08:57
closing since no details how to reproduce

**Closed by SqrTT** 2020-09-16 08:57 UTC

**Comment by flovero** [comment] 2020-09-16 08:58
I stopped vscode auto-update
