### ISSUE TITLE
Prophet suddenly starts to upload too many files

### ISSUE THREAD

**Issue by enis-ismail** [SqrTT/prophet#115] opened 2018-07-25 10:11 UTC
Mostly happens after performing a search in the project. The uploader starts to re-upload too many files which are not modified nor opened in the editor and the changes by the user go to the end of the queue so you have to wait for all files to be re-uploaded which sometimes takes up to 5 mins. 

![image](https://user-images.githubusercontent.com/2821857/43195116-c7e124ec-900c-11e8-9c99-80cbaed3574b.png)

**Comment by enis-ismail** [comment] 2018-07-26 13:23
Hi @SqrTT ,

Today i was testing the following scenarios:
- Adding VSC to the trusted apps no matter if it's public or private connection;
- Adding the whole directory where the project is located to the Excluded files & folders;
- Totally disabling Real-time security;

And the issue still remains. Please let me know if you need anything else related to my system configuration. 

OS: Windows 10 
VSC version: 1.25.0
Prophet Plugin version: 1.0.10

**Comment by enis-ismail** [comment] 2018-08-09 13:12
The issue remains. Mostly happening when searching in the JS and CSS files (even when gulp/grunt is not started and nothing is compiled).

**Comment by SqrTT** [comment] 2018-08-28 14:05
Could you please try to disable all other extensions except prophet and try if it works?

**Comment by shinethazhava** [comment] 2018-10-11 08:14
I have disabled the gulp watch for the css and js still issue exits. 
Do I need to disable any other extentions?

**Comment by umair-farooq-osf** [comment] 2019-01-18 11:59
I am finding this issue as well when I try to globally search any keyword using Ctrl + Shift + F. Is there any fix for this ?

**Comment by SqrTT** [comment] 2019-01-18 13:32
There are nothing I may do. 
The extension relays on the VSCode API for watching [see](https://github.com/SqrTT/prophet/blob/master/src/server/uploadServer.ts#L53). VSCode reports file is changed thus the extension uploads.

**Comment by SqrTT** [comment] 2019-01-18 13:35
Can you try to use `Use Experimental File Watcher` (set checkbox in preferences)?

**Comment by umair-farooq-osf** [comment] 2019-01-18 13:38
Yes I enabled it. Lets me see if that resolves the issue. Thanks

**Comment by enis-ismail** [comment] 2019-01-18 13:58
I also enabled the Experimental File Watcher and I'm not able to reproduce the issue for now. Will keep an eye on it.

**Comment by umair-farooq-osf** [comment] 2019-01-18 13:59
Still it's happening. No effect due to above settings.

**Comment by enis-ismail** [comment] 2019-01-28 08:47
Still happening on my side also. Enabling Experimental File Watcher doesn't solve the issue.

**Comment by shine-thazhava** [comment] 2019-02-05 15:17
Still facing the issue with windows 10.

**Comment by SqrTT** [comment] 2019-02-06 09:33
I'm still not able reproduce the issue. Could you please figure out that's happen and provide PR (if needed)?

**Comment by dshestopalov** [comment] 2019-07-15 19:21
In my case upload error and re-upload of zip files is happening when a lot of files changed
```
... changed files uploaded one by one ...
Error: Error
Trying to re-upload
Connection validated successfully
Current active version is: ...
Start uploading cartridges
Cleanup code version...
... deleting cartridges and re-uploading as zip archives ...
```
![image](https://user-images.githubusercontent.com/3246174/61242630-860c1980-a746-11e9-9c25-cc485f9ab153.png)

which is even make sense if you have small cartridges list (probably will be uploaded faster with compression). I usually do "disable upload - build - enable upload" with keyboard shortcuts ;)
But some projects have a lot of cartridges. And not all of them are changed by build.
Ideal solution for this, as for me, would be some UI to check/un-check cartridges to be taken into account by prophet during upload (analog of eclipse Project References). So developer could prevent cartridge to be uploaded each time if he knows that it won't be changed (i.e. integration cartridges)
I know that it can be controlled in dw.json, but you can't comment anything in JSON, and it is not a  nice UI at all ;)

**Comment by c-ri** [comment] 2019-12-17 14:16
Having to reupload all your cartridges when none has been modified is absolutely awful, especially when your upload speed is low and your project is heavy. 
It would be great if you could do something about this :)

**Comment by SqrTT** [comment] 2019-12-17 15:52
Hi @c-ri 
Are you sure your comment is related to the issue?

**Comment by c-ri** [comment] 2019-12-17 16:04
Yes it is. I have the same problem (random reuploads of unchanged files) and with a slow connexion it's even worse...

**Comment by TravisMcGeehan** [comment] 2020-07-20 19:13
I'm running into this issue as well, a gulp watch task detects SASS files as changed when they are opened.  I only have the prophet extension installed, and if I disable prophet the watch no longer detects a change when the SASS file is opened.  For me it isn't affecting other kinds of files though, only SASS files that are either imported by or import other SASS files.

**Comment by TravisMcGeehan** [comment] 2020-12-29 18:34
this is resolvable in a similar package dw-utils by updating chokidar (which makes sense because it handles tracking filesystem events). Before the update it was only affecting windows users of that library. Not sure how feasible updating that dependency is here, there are a bunch of versions listed in package-lock.

**Comment by SqrTT** [comment] 2020-12-29 19:40
the extension don't use chokidar

**Comment by christophe-bouchy** [comment] 2021-02-25 20:40
Hi all,
I realized a few days ago (while testing issue #272) that I was facing the same issue.

@SqrTT I will try to provide you more info if I find some.
On my side, I confirm it also occurs when launching a search in VSCode.

**Comment by christophe-bouchy** [comment] 2021-04-02 18:08
Hi all and thanks @SqrTT for this fix.
On my side after 2 days of use, I'm unable to find any "abnormal upload" while coding, searching, switching branches etc.

Seems good to me 👍

**Comment by SqrTT** [comment] 2021-04-08 12:44
I believe this may be closed now. Feel free to reopen if still occurs.

**Closed by SqrTT** 2021-04-08 12:44 UTC
