### ISSUE TITLE
Prompted for password after install of VS Code 1.48

### ISSUE THREAD

**Issue by fenomchris** [SqrTT/prophet#248] opened 2020-08-13 21:18 UTC
**Describe the bug**
I am prompted for a password when kicking off an upload

**To Reproduce**
1. Update VS Code to verison 1.48
2. Try to upload code to a sandbox
3. See that you are now prompted for a password

**Expected behavior**
Upload should use the password set in your dw.json file

**Desktop (please complete the following information):**
 - OS: Mac 10.15.6 
 - VSCode version: 1.48.0
 - The extension version 1.3.22

**Comment by SqrTT** [comment] 2020-08-14 09:00
HI @fenomchris 

thank you for reporting. Unfortunately, I can't reproduce by following steps.

Is there any other details missing?

PS. Please clarify amount of dw.json files in your workspaces. Is there chance there are more then 1 and VSCode tries use different than before?

**Comment by valeriykaminskyy** [comment] 2020-08-14 09:03
Same on Windows OS. Update visual studio to the latest version https://code.visualstudio.com/updates/v1_48 and try to upload code. 
Require password issue

**Comment by SqrTT** [comment] 2020-08-14 09:09
for instance paypal contain empty dw,json in repo: https://github.com/SalesforceCommerceCloud/link_paypal/blob/master/dw.json

**Comment by clstopher** [comment] 2020-08-14 13:09
I'm experiencing the same issue on Mac with vscode 1.48; First step was to search for and remove all dw.json files besides my root (found the empty paypal one and one sitting in my storefront_reference_architecture folder that I didn't want it to use anyway).  After removing those files, prompted for a password but then it fails to upload (error is `Error: getaddrinfo ENOTFOUND on`).  Seems like it isn't finding my dw.json file at all.

I've accidentally stumbled on a working configuration - If I have my dw.json file in the storefront_reference_architecture folder of my project, it works (using that file). Also, if I remove the .gitignore rule for my root dw.json file AND have a copy of dw.json in my storefront_reference_architecture folder, it also works but now using my root dw.json file.  If I don't have a dw.json file in the storefront_reference_architecture folder though, it doesn't work.

**Comment by fenomchris** [comment] 2020-08-14 14:14
VSCode version 1.47 still works just fine. Here is a link if anyone needs to roll back:

https://code.visualstudio.com/updates/v1_47

**Comment by fenomchris** [comment] 2020-08-14 14:27
I found a work around. If you run "disable upload" followed by "enable upload" it will eventually work... I had to do it a few times to get it going

**Comment by SqrTT** [comment] 2020-08-14 15:14
Could you guys check if it's fixed in v1.3.23?

**Comment by fenomchris** [comment] 2020-08-14 15:16
v1.3.23 works for me! Thank you for the quick turnaround on the fix! Much appreciated!

**Comment by WMcKibbin** [comment] 2020-08-16 20:21
Had this issue, appears resolved now. No changes to my config since I had this problem last week.

**Comment by SqrTT** [comment] 2020-08-17 08:19
thank you guys.
Closing for now. If issue reappears feel free to reopen.

**Closed by SqrTT** 2020-08-17 08:19 UTC
