### ISSUE TITLE
Editing rendering template freezes Prophet

### ISSUE THREAD

**Issue by pparabuckiTryzens** [SqrTT/prophet#177] opened 2019-06-29 12:39 UTC
Hi,

After editing some of the rendering templates my Prophet with decorators, Prophet crashes and I have to restart VS code and re upload everything. VS code also becomes non responsible. This have happened dozens times.

Best regards,
Petar

**Comment by SqrTT** [comment] 2019-07-01 13:58
Hi @pparabuckiTryzens 
Thank you for reporting. Unfortunately, I'm not facing such issues.
Could you share example of template which freezes editor, please? 
Also detailed step to reproduce would be useful.

PS. Could you check if editor is freezing if other extension are disabled (all except prophet), please?

**Comment by SqrTT** [comment] 2019-10-21 12:41
is this duplicate of https://github.com/SqrTT/prophet/issues/191 ?
@pparabuckiTryzens  could you please confirm if issue is still actual?

**Comment by pparabuckiTryzens** [comment] 2019-10-21 13:06
@SqrTT  it seems that this is fixed now, at least I'm VS code is not crashing :)

**Comment by SqrTT** [comment] 2019-10-21 13:18
thank you for feedback. Closing now. Feel free to reopen if reproduces again.

**Closed by SqrTT** 2019-10-21 13:18 UTC
