### ISSUE TITLE
Icon stuck in perpetual upload cartriges

### ISSUE THREAD

**Issue by AlexandruDinulescu** [SqrTT/prophet#98] opened 2018-04-03 07:40 UTC
Hello

The icon for uploading cartridges at the bottom of VSC (in the bar with the GitHub) is perpetually "uploading cartridges" but I checked the prophet debugger log and it's not doing anything other than watching files.

**Comment by SqrTT** [comment] 2018-04-05 13:58
Hi @AlexandruDinulescu 

thanks for reporting. Could you please share a version of the extension?

**Comment by AlexandruDinulescu** [comment] 2018-04-19 14:14
Hello,

Sorry mate I was in a holiday. This seems to have fixed itself. I'm closing this.

**Comment by SqrTT** [comment] 2018-04-19 16:31
I able to reproduce the issue for current version... so keeping opened, yet

**Comment by SqrTT** [comment] 2018-04-24 12:15
the issue is fixed in `1.0.8` (basically reimplemented via notification window).

Feel free to reopen if still persist.

**Closed by SqrTT** 2018-04-24 12:15 UTC
Labels: bug
