### ISSUE TITLE
Publishing the latest version in the GitHub repository

### ISSUE THREAD

**Issue by jsat** [SqrTT/prophet#331] opened 2022-08-27 03:02 UTC
Hi,
Thank you for providing us with a great extension.

I have one request.

The version of Prophet Debugger offered in Visual Studio Marketplace is 1.4.30.
On the other hand, the version available on GitHub repository, I believe, is 1.3.22.
(as of August 27, 2022)

If possible, I hope you will release the latest version in the GitHub repository in the future.

Sorry if I have misunderstood.

Regards,
jsat

**Comment by SqrTT** [comment] 2022-08-29 07:43
duplicate of https://github.com/SqrTT/prophet/issues/320

**Closed by SqrTT** 2022-08-29 07:43 UTC

**Comment by jsat** [comment] 2022-08-29 07:52
I apologize for any inconvenience caused.
Noted.
