### ISSUE TITLE
"Internal Server Error  undefinedDisconnecting..." when trying to start the debugger

### ISSUE THREAD

**Issue by murgasanu** [SqrTT/prophet#317] opened 2022-03-17 13:26 UTC
Bug description:
    I cannot start the Prophet Debugger because it gives me this error in the "Debug console": "Internal Server Error  undefinedDisconnecting..."  and in the Sandbox logs I have this error: "ERROR http-nio-10.51.179.202-10052-exec-3 com.demandware.core.script.dapi.DebuggerServlet - TEMPORARY 8016c74bf5 0051a216936823b132f492b6b4 3822859179920178176 - Failed to process request '/servlet/s/-/dw/debugger/v2_0/client', responding HTTP 500 INTERNAL_SERVER_ERROR fault message
Stack trace [<ref:602799d32d579415293b50c8f2f90465>]()".
    I have tried anything: restarting VS Code, restarting the Sandbox, re-upload the code wth Prophet(uploader is working fine), installed an older version of Prophet, switched the code version, but non of them worked.
    It was working yesterday, the problem occured this morning.

Steps to reproduce:
- Upload the cartidges
- Place a breakpoint in the desired area (an eligible part, such as in a controller)
- Try to start the debugger

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]:  macOS Monterey 12.3, but tried it before today with 12.2 version as well and it din't work.
 - VSCode version: version 1.65
 - The extension version [e.g. 22]: Prophet version 1.4.27

**Comment by SqrTT** [comment] 2022-03-17 13:35
seems this is duplicate of #313
In most cases this happen due to mixup cases in username (dw.json). (username is case sensitive)

**Comment by murgasanu** [comment] 2022-03-17 14:16
Thanks for the answer. Indeed the problem was that the e-mail was written with upper case first letter in my Sandbox, in User List. I have changed this as well in the dw.json file and it is working again. It's funny that untl today, this was no issue :)

**Closed** 2022-03-17 14:26 UTC
