### ISSUE TITLE
v1.2.2+ Breaks SFRA sandboxes during upload all

### ISSUE THREAD

**Issue by Eneris** [SqrTT/prophet#198] opened 2019-10-28 14:41 UTC
**Describe the bug**
Upload all process breaks SFRA site. Controllers can't find module "server"

**To Reproduce**
Steps to reproduce the behaviour:
1. Run upload all
2. Try to open any part of SFRA page which goes thru controller
3. Server requests return 500 code

**Expected behaviour**
Be able to load pages

**Screenshots**
`Exception occurred during request processing: ScriptingException Error: Module "server" not found.`

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - VSCode version: 1.39.2
 - The extension version: 1.2.2 and 1.2.3

**Additional context**
On file change upload works as expected

**Comment by Eneris** [comment] 2019-10-28 14:42
When I revert Prophet version to v1.2.1, upload all works fine

**Comment by Eneris** [comment] 2019-10-28 14:42
Also, during upload, no errors appear

**Comment by SqrTT** [comment] 2019-10-28 14:52
Is this duplicate of #197 ?

**Comment by Eneris** [comment] 2019-10-29 14:49
Don't think so. There is no cartridge that would be implementing or overriding "server" module.
I did a quick test.
1.2.1 - uploads 57 cartridges - no error
1.2.3 - uploads 57 cartridges - 500 error
1.2.4 - same like 1.2.3

**Comment by SqrTT** [comment] 2019-10-29 15:13
is `modules` folder uploaded to sandbox?

**Comment by Eneris** [comment] 2019-10-29 16:36
Nope no errors (sorry forgot to mention it in description)

**Comment by xhallix** [comment] 2019-10-31 13:46
@Eneris can you check if you have the same cartridges somewhere twice?
Our issue was that we installed sfra by npm and so there was in issue with having the files in the node modules folder and in the directory also. Maybe it is  just node_modules folder which causes such issues

I think somethings changed with File lookup drin v1.2.1 to v1.2.3

**Comment by challmannsf** [comment] 2019-10-31 13:48
@Eneris can you check if you have the same cartridges somewhere twice?
Our issue was that we installed sfra by npm and so there was in issue with having the files in the node modules folder and in the directory also. Maybe it is just node_modules folder which causes such issues

I think somethings changed with File lookup drin v1.2.1 to v1.2.3

**Comment by SqrTT** [comment] 2019-10-31 13:53
Lookup wasn't changes. Changed only deletion of cartridges. Previously all was removed before upload. But in latest versions old cartridge deletion is proceed right before unzipping new cartridge. So previously duplicated cartridges were just overridden but now they are conflicting.

@Eneris Could you share your upload log, please?

**Comment by challmannsf** [comment] 2019-10-31 13:55
@SqrTT since I can reproduce this error I would be happy to help out if you like. 

I just did sone debugging sometime ago and saw that the cartridges are uploaded but then are removed again

**Comment by Eneris** [comment] 2019-10-31 14:39
@SqrTT  @challmannsf  We do install sfra base cartridge by npm, run compile on them and copy cartridges into project cartridges. So all cartridges are in root `/catridges` folder

Example structure:

- /cartridges
  - ./modules
  - ./app_storefront_base
  - ./app_custom_*
- /node_modules/sfra/cartridges
  - ./app_storefront_base
  - ./modules

**Comment by Eneris** [comment] 2019-10-31 14:47
Here is log for Upload all (minus our custom cartridges ;))

`Starting...
Using config file '/dw.json'
Connection validated successfully
Current active version is: develop
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting remote zip (if any)
[app_storefront_base] Zipping
[app_storefront_base] Sending zip to remote
[modules] Deleting remote zip (if any)
[modules] Zipping
[app_storefront_base] Remove remote cartridge before extract
[modules] Sending zip to remote
[modules] Remove remote cartridge before extract
[modules] Unzipping remote zip
[modules] Deleting remote zip...
[app_storefront_base] Deleting remote zip (if any)
[app_storefront_base] Zipping
[modules] Deleting remote zip (if any)
[modules] Zipping
[app_storefront_base] Sending zip to remote
[modules] Sending zip to remote
[app_storefront_base] Remove remote cartridge before extract
[modules] Remove remote cartridge before extract
[modules] Unzipping remote zip
[modules] Deleting remote zip...
[app_storefront_base] Unzipping remote zip
[app_storefront_base] Unzipping remote zip
[app_storefront_base] Deleting remote zip...
[app_storefront_base] Deleting remote zip...
Cartridges uploaded successfully
Watching files
`

**Comment by challmannsf** [comment] 2019-10-31 15:22
> @SqrTT @challmannsf We do install sfra base cartridge by npm, run compile on them and copy cartridges into project cartridges. So all cartridges are in root `/catridges` folder
> 
> Example structure:
> 
> * /cartridges
>   
>   * ./modules
>   * ./app_storefront_base
>   * ./app_custom_*
> * /node_modules/sfra/cartridges
>   
>   * ./app_storefront_base
>   * ./modules

@Eneris exactly the issue I faced. If you move sfra out of node modules it does work. Just copy it to the dir and remove it from node_modules after that

**Comment by challmannsf** [comment] 2019-10-31 15:25
> @challmannsf I'll be appreciated if you could target this issue :)

Sure, since it is easy to reproduce with node_modules folder I will catch it up 👌

**Comment by SqrTT** [comment] 2019-10-31 17:30
What behavior of extension is expected  in case found cartridges with same name?

**Comment by challmannsf** [comment] 2019-10-31 18:22
> What behavior of extension is expected in case found cartridges with same name?

@SqrTT I think in this case there is no duplication. I believe that uploading cartridges which resides in node_modules is the issue.

**Comment by SqrTT** [comment] 2019-11-01 08:33
well this is long history...  short version, we had fighting were disagree if cartridges should be detected in `node_modules` and as you see `node_module` won.

**Comment by challmannsf** [comment] 2019-11-01 16:44
@SqrTT I see that `node_modules` are set to an ignore list.
What is the expected behavior here?
Allow to upload cartridges which resides in `node_modules` or do not allow such uploads?

**Comment by challmannsf** [comment] 2019-11-01 18:15
#204 first draft

**Comment by amezick** [comment] 2019-11-26 18:54
Any update on this issue?

**Comment by challmannsf** [comment] 2019-11-26 19:03
@SqrTT @amezick the PR #204 was updated and will fix it

**Comment by SqrTT** [comment] 2019-11-27 09:06
sorry, currently I don't have enough of time. Unfortunately, PR #204 don't solve issue with cartridge duplicates.

**Comment by SqrTT** [comment] 2020-02-10 08:57
@challmannsf  add warning for this case so cartridge duplication would not be hard to findout

**Closed by SqrTT** 2020-02-10 08:57 UTC
